### PR TITLE
[WIP] Updated Celluloid Videos

### PR DESCRIPTION
**Pull request by chirag-ghosh**
Changes also include changes due to automatic prettier linting.

[Demo Link](https://www.chiragghosh.me/tfps/)

### CODE REVIEW

**Comment by rashil2000** [comment]
Please revert the formatting changes - only keep the video id changes

**Comment by chirag828049** [comment]
But formatting won't affect the working of code right ?

**Comment by rashil2000** [comment]
It won't, that's why I asked to revert it. We can format later.

**Comment by chirag828049** [comment]
Some more updates need to be done as said by Governor.

**Comment by rashil2000** [comment]
Okay, mark it as Draft till it is done

**Comment by chirag828049** [comment]
I don't have write access. I guess only you can convert to draft

**Comment by chirag828049** [comment]
Done with the changes,

**Pull request merged**
